### ISSUE TITLE
the search method doesn't return any results

### ISSUE THREAD

**Issue by khalilbenkhaled** [hemantapkh/1337x#7]

**Comment by khalilbenkhaled** [comment]
im working on a fix

**Comment by hemantapkh** [comment]
Just checked and everything is working fine for me. Can you check if **www.1377x.to** is working fine in your browser?

**Comment by khalilbenkhaled** [comment]
yes, It's working fine. The function doesn't work tho. 
I submitted a pull request fixing it, you should check it out.
It's a really small issue.

**Comment by hemantapkh** [comment]
search method is working fine for me. Can you send the screenshot?

**Comment by khalilbenkhaled** [comment]
![image](https://user-images.githubusercontent.com/80462097/159160872-755ee9ab-d35a-4efd-8fe7-123a125815f3.png)
the result is always empty 
I ran  the harry potter example in the docs. 
if it's working for you then it must be just  a me  problem.

**Comment by hemantapkh** [comment]
Can you also show the content of `test.py` file?

**Comment by FrancescoGrazioso** [comment]
having the same error, i pass he cookie from chrome but get 403 - unauthorized on the search response
